[package]
name = "my_models"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "1.0.0", features = ["tokio-comp", "streams"], optional = true}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[features]
default = []
native = ["redis"]
