[package]
name = "work_2_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
lazy_static = "1.5.0"
prometheus = "0.14.0"
tokio = { version = "1.48.0", features = [ "default", "rt-multi-thread" ] }

