[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
elasticsearch = "9.1.0-alpha.1"
reqwest = "0.12.26"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
