services:

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  db:
    image: postgres:15.15-alpine3.22
    container_name: db
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      - "DATA_SOURCE_URI=db:5432/postgres?sslmode=disable"
      - "DATA_SOURCE_USER=postgres"
      - "DATA_SOURCE_PASS=postgres"
    ports:
      - "9187:9187"
