
services:

  db:
    image: postgres:15.15-alpine3.22 
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=my_tauri_app_db"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  redis: 
    image: redis:alpine3.22
    ports:
      - "6379:6379"
    
  